_line_num: 1
_program
  _line_num: 1
  _class
    Main
    _inherits: IO
    _file_name: "assignment.test"
    (
    _line_num: 2
    _attr
      x
      : Int
      _line_num: 2
      _no_expr
      : Int
    _line_num: 3
    _attr
      y
      : String
      _line_num: 3
      _no_expr
      : String
    _line_num: 4
    _attr
      f
      : Foo
      _line_num: 4
      _no_expr
      : Foo
    _line_num: 5
    _method
      main (
      )
      : Object
      _line_num: 5
      _block
        _line_num: 6
        _assign
          x
          _line_num: 6
          _int
            3
          : Int
        : Int
        _line_num: 6
        _assign
          x
          _line_num: 6
          _int
            5
          : Int
        : Int
        _line_num: 6
        _assign
          y
          _line_num: 6
          _string
            "test"
          : String
        : String
        _line_num: 6
        _assign
          f
          _line_num: 6
          _new
            Foo
          : Foo
        : Foo
      : Foo
    _line_num: 8
    _method
      foo (
      )
      : String
      _line_num: 8
      _string
        "test"
      : String
    )
  _line_num: 10
  _class
    Foo
    _inherits: Object
    _file_name: "assignment.test"
    (
    _line_num: 11
    _attr
      x
      : Int
      _line_num: 11
      _int
        3
      : Int
    )
