_line_num: 1
_program
  _line_num: 1
  _class
    Main
    _inherits: Object
    _file_name: "basicclassestree.test"
    (
    _line_num: 1
    _method
      main (
      )
      : Int
      _line_num: 1
      _int
        0
      : Int
    )
  _line_num: 3
  _class
    A
    _inherits: Object
    _file_name: "basicclassestree.test"
    (
    _line_num: 4
    _attr
      a
      : Object
      _line_num: 4
      _int
        0
      : Int
    _line_num: 5
    _attr
      b
      : Object
      _line_num: 5
      _string
        ""
      : String
    _line_num: 6
    _attr
      c
      : Object
      _line_num: 6
      _bool
        true
      : Bool
    )
