_line_num: 1
_program
  _line_num: 1
  _class
    Main
    _inherits: Object
    _file_name: "basic.test"
    (
    _line_num: 2
    _method
      main (
      )
      : Object
      _line_num: 2
      _block
        _line_num: 2
        _dispatch
          _is_tail: false
          _line_num: 2
          _int
            5
          : Int
          copy (
          )
        : Int
        _line_num: 2
        _dispatch
          _is_tail: false
          _line_num: 2
          _string
            "test"
          : String
          copy (
          )
        : String
        _line_num: 2
        _dispatch
          _is_tail: false
          _line_num: 2
          _bool
            true
          : Bool
          copy (
          )
        : Bool
        _line_num: 3
        _dispatch
          _is_tail: true
          _line_num: 3
          _string
            "test"
          : String
          length (
          )
        : Int
      : Int
    )
