_line_num: 5
_program
  _line_num: 5
  _class
    CellularAutomaton
    _inherits: IO
    _file_name: "cells.cl.test"
    (
    _line_num: 6
    _attr
      population_map
      : String
      _line_num: 6
      _no_expr
      : String
    _line_num: 8
    _method
      init (
      _line_num: 8
      _formal
        map
        : String
      )
      : SELF_TYPE
      _line_num: 9
      _block
        _line_num: 10
        _assign
          population_map
          _line_num: 10
          _object
            map
          : String
        : String
        _line_num: 11
        _object
          self
        : SELF_TYPE
      : SELF_TYPE
    _line_num: 15
    _method
      print (
      )
      : SELF_TYPE
      _line_num: 16
      _block
        _line_num: 17
        _dispatch
          _is_tail: false
          _line_num: 17
          _object
            self
          : SELF_TYPE
          out_string (
          _line_num: 17
          _dispatch
            _is_tail: false
            _line_num: 17
            _object
              population_map
            : String
            concat (
            _line_num: 17
            _string
              "\n"
            : String
            )
          : String
          )
        : SELF_TYPE
        _line_num: 18
        _object
          self
        : SELF_TYPE
      : SELF_TYPE
    _line_num: 22
    _method
      num_cells (
      )
      : Int
      _line_num: 23
      _dispatch
        _is_tail: true
        _line_num: 23
        _object
          population_map
        : String
        length (
        )
      : Int
    _line_num: 26
    _method
      cell (
      _line_num: 26
      _formal
        position
        : Int
      )
      : String
      _line_num: 27
      _dispatch
        _is_tail: true
        _line_num: 27
        _object
          population_map
        : String
        substr (
        _line_num: 27
        _object
          position
        : Int
        _line_num: 27
        _int
          1
        : Int
        )
      : String
    _line_num: 30
    _method
      cell_left_neighbor (
      _line_num: 30
      _formal
        position
        : Int
      )
      : String
      _line_num: 31
      _cond
        _line_num: 31
        _eq
          _line_num: 31
          _object
            position
          : Int
          _line_num: 31
          _int
            0
          : Int
        : Bool
        _line_num: 32
        _dispatch
          _is_tail: true
          _line_num: 32
          _object
            self
          : SELF_TYPE
          cell (
          _line_num: 32
          _sub
            _line_num: 32
            _dispatch
              _is_tail: false
              _line_num: 32
              _object
                self
              : SELF_TYPE
              num_cells (
              )
            : Int
            _line_num: 32
            _int
              1
            : Int
          : Int
          )
        : String
        _line_num: 34
        _dispatch
          _is_tail: true
          _line_num: 34
          _object
            self
          : SELF_TYPE
          cell (
          _line_num: 34
          _sub
            _line_num: 34
            _object
              position
            : Int
            _line_num: 34
            _int
              1
            : Int
          : Int
          )
        : String
      : String
    _line_num: 38
    _method
      cell_right_neighbor (
      _line_num: 38
      _formal
        position
        : Int
      )
      : String
      _line_num: 39
      _cond
        _line_num: 39
        _eq
          _line_num: 39
          _object
            position
          : Int
          _line_num: 39
          _sub
            _line_num: 39
            _dispatch
              _is_tail: false
              _line_num: 39
              _object
                self
              : SELF_TYPE
              num_cells (
              )
            : Int
            _line_num: 39
            _int
              1
            : Int
          : Int
        : Bool
        _line_num: 40
        _dispatch
          _is_tail: true
          _line_num: 40
          _object
            self
          : SELF_TYPE
          cell (
          _line_num: 40
          _int
            0
          : Int
          )
        : String
        _line_num: 42
        _dispatch
          _is_tail: true
          _line_num: 42
          _object
            self
          : SELF_TYPE
          cell (
          _line_num: 42
          _plus
            _line_num: 42
            _object
              position
            : Int
            _line_num: 42
            _int
              1
            : Int
          : Int
          )
        : String
      : String
    _line_num: 48
    _method
      cell_at_next_evolution (
      _line_num: 48
      _formal
        position
        : Int
      )
      : String
      _line_num: 49
      _cond
        _line_num: 49
        _eq
          _line_num: 49
          _plus
            _line_num: 49
            _plus
              _line_num: 49
              _cond
                _line_num: 49
                _eq
                  _line_num: 49
                  _dispatch
                    _is_tail: false
                    _line_num: 49
                    _object
                      self
                    : SELF_TYPE
                    cell (
                    _line_num: 49
                    _object
                      position
                    : Int
                    )
                  : String
                  _line_num: 49
                  _string
                    "X"
                  : String
                : Bool
                _line_num: 49
                _int
                  1
                : Int
                _line_num: 49
                _int
                  0
                : Int
              : Int
              _line_num: 50
              _cond
                _line_num: 50
                _eq
                  _line_num: 50
                  _dispatch
                    _is_tail: false
                    _line_num: 50
                    _object
                      self
                    : SELF_TYPE
                    cell_left_neighbor (
                    _line_num: 50
                    _object
                      position
                    : Int
                    )
                  : String
                  _line_num: 50
                  _string
                    "X"
                  : String
                : Bool
                _line_num: 50
                _int
                  1
                : Int
                _line_num: 50
                _int
                  0
                : Int
              : Int
            : Int
            _line_num: 51
            _cond
              _line_num: 51
              _eq
                _line_num: 51
                _dispatch
                  _is_tail: false
                  _line_num: 51
                  _object
                    self
                  : SELF_TYPE
                  cell_right_neighbor (
                  _line_num: 51
                  _object
                    position
                  : Int
                  )
                : String
                _line_num: 51
                _string
                  "X"
                : String
              : Bool
              _line_num: 51
              _int
                1
              : Int
              _line_num: 51
              _int
                0
              : Int
            : Int
          : Int
          _line_num: 52
          _int
            1
          : Int
        : Bool
        _line_num: 54
        _string
          "X"
        : String
        _line_num: 56
        _string
          "."
        : String
      : String
    _line_num: 60
    _method
      evolve (
      )
      : SELF_TYPE
      _line_num: 61
      _let
        position
        : Int
        _line_num: 61
        _no_expr
        : Int
        _line_num: 62
        _let
          num
          : Int
          _line_num: 62
          _dispatch
            _is_tail: false
            _line_num: 62
            _object
              self
            : SELF_TYPE
            num_cells (
            )
          : Int
          _line_num: 63
          _let
            temp
            : String
            _line_num: 63
            _no_expr
            : String
            _line_num: 64
            _block
              _line_num: 65
              _loop
                _line_num: 65
                _lt
                  _line_num: 65
                  _object
                    position
                  : Int
                  _line_num: 65
                  _object
                    num
                  : Int
                : Bool
                _line_num: 66
                _block
                  _line_num: 67
                  _assign
                    temp
                    _line_num: 67
                    _dispatch
                      _is_tail: false
                      _line_num: 67
                      _object
                        temp
                      : String
                      concat (
                      _line_num: 67
                      _dispatch
                        _is_tail: false
                        _line_num: 67
                        _object
                          self
                        : SELF_TYPE
                        cell_at_next_evolution (
                        _line_num: 67
                        _object
                          position
                        : Int
                        )
                      : String
                      )
                    : String
                  : String
                  _line_num: 68
                  _assign
                    position
                    _line_num: 68
                    _plus
                      _line_num: 68
                      _object
                        position
                      : Int
                      _line_num: 68
                      _int
                        1
                      : Int
                    : Int
                  : Int
                : Int
              : Object
              _line_num: 71
              _assign
                population_map
                _line_num: 71
                _object
                  temp
                : String
              : String
              _line_num: 72
              _object
                self
              : SELF_TYPE
            : SELF_TYPE
          : SELF_TYPE
        : SELF_TYPE
      : SELF_TYPE
    )
  _line_num: 78
  _class
    Main
    _inherits: Object
    _file_name: "cells.cl.test"
    (
    _line_num: 79
    _attr
      cells
      : CellularAutomaton
      _line_num: 79
      _no_expr
      : CellularAutomaton
    _line_num: 81
    _method
      main (
      )
      : SELF_TYPE
      _line_num: 82
      _block
        _line_num: 83
        _assign
          cells
          _line_num: 83
          _dispatch
            _is_tail: false
            _line_num: 83
            _new
              CellularAutomaton
            : CellularAutomaton
            init (
            _line_num: 83
            _string
              "         X         "
            : String
            )
          : CellularAutomaton
        : CellularAutomaton
        _line_num: 84
        _dispatch
          _is_tail: false
          _line_num: 84
          _object
            cells
          : CellularAutomaton
          print (
          )
        : CellularAutomaton
        _line_num: 85
        _let
          countdown
          : Int
          _line_num: 85
          _int
            20
          : Int
          _line_num: 86
          _loop
            _line_num: 86
            _lt
              _line_num: 86
              _int
                0
              : Int
              _line_num: 86
              _object
                countdown
              : Int
            : Bool
            _line_num: 87
            _block
              _line_num: 88
              _dispatch
                _is_tail: false
                _line_num: 88
                _object
                  cells
                : CellularAutomaton
                evolve (
                )
              : CellularAutomaton
              _line_num: 89
              _dispatch
                _is_tail: false
                _line_num: 89
                _object
                  cells
                : CellularAutomaton
                print (
                )
              : CellularAutomaton
              _line_num: 90
              _assign
                countdown
                _line_num: 90
                _sub
                  _line_num: 90
                  _object
                    countdown
                  : Int
                  _line_num: 90
                  _int
                    1
                  : Int
                : Int
              : Int
            : Int
          : Object
        : Object
        _line_num: 94
        _object
          self
        : SELF_TYPE
      : SELF_TYPE
    )
