_line_num: 1
_program
  _line_num: 1
  _class
    A
    _inherits: Object
    _file_name: "classes.test"
    (
    _line_num: 3
    _attr
      a
      : Int
      _line_num: 3
      _int
        0
      : Int
    _line_num: 4
    _attr
      d
      : Int
      _line_num: 4
      _int
        1
      : Int
    _line_num: 5
    _method
      f (
      )
      : Int
      _line_num: 5
      _assign
        a
        _line_num: 5
        _plus
          _line_num: 5
          _object
            a
          : Int
          _line_num: 5
          _object
            d
          : Int
        : Int
      : Int
    )
  _line_num: 9
  _class
    B
    _inherits: A
    _file_name: "classes.test"
    (
    _line_num: 10
    _attr
      b
      : Int
      _line_num: 10
      _int
        2
      : Int
    _line_num: 11
    _method
      f (
      )
      : Int
      _line_num: 11
      _object
        a
      : Int
    _line_num: 12
    _method
      g (
      )
      : Int
      _line_num: 12
      _assign
        a
        _line_num: 12
        _sub
          _line_num: 12
          _object
            a
          : Int
          _line_num: 12
          _object
            b
          : Int
        : Int
      : Int
    )
  _line_num: 15
  _class
    C
    _inherits: A
    _file_name: "classes.test"
    (
    _line_num: 16
    _attr
      c
      : Int
      _line_num: 16
      _int
        3
      : Int
    _line_num: 17
    _method
      h (
      )
      : Int
      _line_num: 17
      _assign
        a
        _line_num: 17
        _sub
          _line_num: 17
          _object
            a
          : Int
          _line_num: 17
          _object
            c
          : Int
        : Int
      : Int
    )
  _line_num: 19
  _class
    Main
    _inherits: Object
    _file_name: "classes.test"
    (
    _line_num: 19
    _method
      main (
      )
      : Int
      _line_num: 19
      _int
        6
      : Int
    )
