_line_num: 1
_program
  _line_num: 1
  _class
    A
    _inherits: Object
    _file_name: "comparisons.test"
    (
    _line_num: 2
    _method
      foo (
      _line_num: 2
      _formal
        a
        : A
      )
      : Bool
      _line_num: 2
      _block
        _line_num: 2
        _lt
          _line_num: 2
          _int
            6
          : Int
          _line_num: 2
          _int
            7
          : Int
        : Bool
        _line_num: 2
        _leq
          _line_num: 2
          _int
            6
          : Int
          _line_num: 2
          _int
            7
          : Int
        : Bool
        _line_num: 2
        _comp
          _line_num: 2
          _bool
            true
          : Bool
        : Bool
      : Bool
    )
  _line_num: 5
  _class
    Main
    _inherits: Object
    _file_name: "comparisons.test"
    (
    _line_num: 5
    _method
      main (
      )
      : Int
      _line_num: 5
      _int
        6
      : Int
    )
