_line_num: 1
_program
  _line_num: 1
  _class
    Main
    _inherits: Object
    _file_name: "compare.test"
    (
    _line_num: 1
    _method
      main (
      )
      : Int
      _line_num: 1
      _int
        0
      : Int
    )
  _line_num: 3
  _class
    A
    _inherits: Object
    _file_name: "compare.test"
    (
    )
  _line_num: 4
  _class
    B
    _inherits: Object
    _file_name: "compare.test"
    (
    )
  _line_num: 5
  _class
    C
    _inherits: Object
    _file_name: "compare.test"
    (
    _line_num: 6
    _attr
      a
      : A
      _line_num: 6
      _no_expr
      : A
    _line_num: 7
    _attr
      b
      : B
      _line_num: 7
      _no_expr
      : B
    _line_num: 9
    _method
      compare (
      )
      : Bool
      _line_num: 10
      _eq
        _line_num: 10
        _object
          a
        : A
        _line_num: 10
        _object
          b
        : B
      : Bool
    )
