_line_num: 1
_program
  _line_num: 1
  _class
    Main
    _inherits: Object
    _file_name: "dispatch.test"
    (
    _line_num: 2
    _method
      main (
      )
      : Object
      _line_num: 2
      _int
        42
      : Int
    )
  _line_num: 5
  _class
    A
    _inherits: Object
    _file_name: "dispatch.test"
    (
    _line_num: 6
    _method
      foo (
      _line_num: 6
      _formal
        a
        Int
      _line_num: 6
      _formal
        b
        B
      _line_num: 6
      _formal
        c
        A
      _line_num: 6
      _formal
        d
        B
      )
      : A
      _line_num: 7
      _object
        self
      : SELF_TYPE
    )
  _line_num: 12
  _class
    B
    _inherits: A
    _file_name: "dispatch.test"
    (
    _line_num: 14
    _method
      moo (
      )
      : A
      _line_num: 15
      _let
        b
        B
        _line_num: 15
        _new
          B
        : B
        _line_num: 16
        _dispatch
          _is_tail: true
          _line_num: 16
          _object
            self
          : SELF_TYPE
          foo (
          _line_num: 16
          _int
            4
          : Int
          _line_num: 16
          _object
            b
          : B
          _line_num: 16
          _object
            b
          : B
          _line_num: 16
          _object
            b
          : B
          )
        : A
      : A
    )
