_line_num: 1
_program
  _line_num: 1
  _class
    Main
    _inherits: Object
    _file_name: "expressionblock.test"
    (
    _line_num: 1
    _method
      main (
      )
      : Int
      _line_num: 1
      _int
        0
      : Int
    )
  _line_num: 3
  _class
    A
    _inherits: Object
    _file_name: "expressionblock.test"
    (
    _line_num: 4
    _method
      foo (
      )
      : Int
      _line_num: 4
      _block
        _line_num: 4
        _object
          self
        : SELF_TYPE
        _line_num: 4
        _string
          "hello"
        : String
        _line_num: 4
        _bool
          true
        : Bool
        _line_num: 4
        _int
          1
        : Int
      : Int
    )
