_line_num: 1
_program
  _line_num: 1
  _class
    A
    _inherits: B
    _file_name: "forwardinherits.test"
    (
    _line_num: 3
    _attr
      foo
      : Int
      _line_num: 3
      _no_expr
      : Int
    )
  _line_num: 7
  _class
    B
    _inherits: Object
    _file_name: "forwardinherits.test"
    (
    _line_num: 9
    _attr
      bar
      : Int
      _line_num: 9
      _no_expr
      : Int
    )
  _line_num: 12
  _class
    Main
    _inherits: Object
    _file_name: "forwardinherits.test"
    (
    _line_num: 12
    _method
      main (
      )
      : Int
      _line_num: 12
      _int
        6
      : Int
    )
