_line_num: 3
_program
  _line_num: 3
  _class
    Foo
    _inherits: Bazz
    _file_name: "hairyscary.cl.test"
    (
    _line_num: 4
    _attr
      a
      : Razz
      _line_num: 4
      _typcase
        _line_num: 4
        _object
          self
        : SELF_TYPE
        _line_num: 5
        _branch
          n
          : Razz
          _line_num: 5
          _new
            Bar
          : Bar
        _line_num: 6
        _branch
          n
          : Foo
          _line_num: 6
          _new
            Razz
          : Razz
        _line_num: 7
        _branch
          n
          : Bar
          _line_num: 7
          _object
            n
          : Bar
      : Razz
    _line_num: 10
    _attr
      b
      : Int
      _line_num: 10
      _plus
        _line_num: 10
        _plus
          _line_num: 10
          _plus
            _line_num: 10
            _dispatch
              _is_tail: false
              _line_num: 10
              _object
                a
              : Razz
              doh (
              )
            : Int
            _line_num: 10
            _dispatch
              _is_tail: false
              _line_num: 10
              _object
                g
              : Foo
              doh (
              )
            : Int
          : Int
          _line_num: 10
          _dispatch
            _is_tail: false
            _line_num: 10
            _object
              self
            : SELF_TYPE
            doh (
            )
          : Int
        : Int
        _line_num: 10
        _dispatch
          _is_tail: false
          _line_num: 10
          _object
            self
          : SELF_TYPE
          printh (
          )
        : Int
      : Int
    _line_num: 12
    _method
      doh (
      )
      : Int
      _line_num: 12
      _let
        i
        : Int
        _line_num: 12
        _object
          h
        : Int
        _line_num: 12
        _block
          _line_num: 12
          _assign
            h
            _line_num: 12
            _plus
              _line_num: 12
              _object
                h
              : Int
              _line_num: 12
              _int
                2
              : Int
            : Int
          : Int
          _line_num: 12
          _object
            i
          : Int
        : Int
      : Int
    )
  _line_num: 16
  _class
    Bar
    _inherits: Razz
    _file_name: "hairyscary.cl.test"
    (
    _line_num: 18
    _attr
      c
      : Int
      _line_num: 18
      _dispatch
        _is_tail: false
        _line_num: 18
        _object
          self
        : SELF_TYPE
        doh (
        )
      : Int
    _line_num: 20
    _attr
      d
      : Object
      _line_num: 20
      _dispatch
        _is_tail: false
        _line_num: 20
        _object
          self
        : SELF_TYPE
        printh (
        )
      : Int
    )
  _line_num: 24
  _class
    Razz
    _inherits: Foo
    _file_name: "hairyscary.cl.test"
    (
    _line_num: 26
    _attr
      e
      : Bar
      _line_num: 26
      _typcase
        _line_num: 26
        _object
          self
        : SELF_TYPE
        _line_num: 27
        _branch
          n
          : Razz
          _line_num: 27
          _new
            Bar
          : Bar
        _line_num: 28
        _branch
          n
          : Bar
          _line_num: 28
          _object
            n
          : Bar
      : Bar
    _line_num: 31
    _attr
      f
      : Int
      _line_num: 31
      _plus
        _line_num: 31
        _plus
          _line_num: 31
          _plus
            _line_num: 31
            _plus
              _line_num: 31
              _static_dispatch
                _is_tail: false
                _line_num: 31
                _object
                  a
                : Razz
                Bazz
                doh (
                )
              : Int
              _line_num: 31
              _dispatch
                _is_tail: false
                _line_num: 31
                _object
                  g
                : Foo
                doh (
                )
              : Int
            : Int
            _line_num: 31
            _dispatch
              _is_tail: false
              _line_num: 31
              _object
                e
              : Bar
              doh (
              )
            : Int
          : Int
          _line_num: 31
          _dispatch
            _is_tail: false
            _line_num: 31
            _object
              self
            : SELF_TYPE
            doh (
            )
          : Int
        : Int
        _line_num: 31
        _dispatch
          _is_tail: false
          _line_num: 31
          _object
            self
          : SELF_TYPE
          printh (
          )
        : Int
      : Int
    )
  _line_num: 35
  _class
    Bazz
    _inherits: IO
    _file_name: "hairyscary.cl.test"
    (
    _line_num: 37
    _attr
      h
      : Int
      _line_num: 37
      _int
        1
      : Int
    _line_num: 39
    _attr
      g
      : Foo
      _line_num: 39
      _typcase
        _line_num: 39
        _object
          self
        : SELF_TYPE
        _line_num: 40
        _branch
          n
          : Bazz
          _line_num: 40
          _new
            Foo
          : Foo
        _line_num: 41
        _branch
          n
          : Razz
          _line_num: 41
          _new
            Bar
          : Bar
        _line_num: 42
        _branch
          n
          : Foo
          _line_num: 42
          _new
            Razz
          : Razz
        _line_num: 43
        _branch
          n
          : Bar
          _line_num: 43
          _object
            n
          : Bar
      : Foo
    _line_num: 46
    _attr
      i
      : Object
      _line_num: 46
      _dispatch
        _is_tail: false
        _line_num: 46
        _object
          self
        : SELF_TYPE
        printh (
        )
      : Int
    _line_num: 48
    _method
      printh (
      )
      : Int
      _line_num: 48
      _block
        _line_num: 48
        _dispatch
          _is_tail: false
          _line_num: 48
          _object
            self
          : SELF_TYPE
          out_int (
          _line_num: 48
          _object
            h
          : Int
          )
        : SELF_TYPE
        _line_num: 48
        _int
          0
        : Int
      : Int
    _line_num: 50
    _method
      doh (
      )
      : Int
      _line_num: 50
      _let
        i
        : Int
        _line_num: 50
        _object
          h
        : Int
        _line_num: 50
        _block
          _line_num: 50
          _assign
            h
            _line_num: 50
            _plus
              _line_num: 50
              _object
                h
              : Int
              _line_num: 50
              _int
                1
              : Int
            : Int
          : Int
          _line_num: 50
          _object
            i
          : Int
        : Int
      : Int
    )
  _line_num: 54
  _class
    Main
    _inherits: Object
    _file_name: "hairyscary.cl.test"
    (
    _line_num: 55
    _attr
      a
      : Bazz
      _line_num: 55
      _new
        Bazz
      : Bazz
    _line_num: 56
    _attr
      b
      : Foo
      _line_num: 56
      _new
        Foo
      : Foo
    _line_num: 57
    _attr
      c
      : Razz
      _line_num: 57
      _new
        Razz
      : Razz
    _line_num: 58
    _attr
      d
      : Bar
      _line_num: 58
      _new
        Bar
      : Bar
    _line_num: 60
    _method
      main (
      )
      : String
      _line_num: 60
      _string
        "do nothing"
      : String
    )
