_line_num: 1
_program
  _line_num: 1
  _class
    Main
    _inherits: IO
    _file_name: "if.test"
    (
    _line_num: 2
    _attr
      x
      : Int
      _line_num: 2
      _no_expr
      : Int
    _line_num: 3
    _method
      main (
      )
      : Object
      _line_num: 3
      _block
        _line_num: 4
        _cond
          _line_num: 4
          _eq
            _line_num: 4
            _plus
              _line_num: 4
              _let
                x
                : Int
                _line_num: 4
                _int
                  5
                : Int
                _line_num: 4
                _plus
                  _line_num: 4
                  _object
                    x
                  : Int
                  _line_num: 4
                  _int
                    3
                  : Int
                : Int
              : Int
              _line_num: 4
              _int
                3
              : Int
            : Int
            _line_num: 4
            _int
              9
            : Int
          : Bool
          _line_num: 4
          _int
            3
          : Int
          _line_num: 4
          _dispatch
            _is_tail: true
            _line_num: 4
            _object
              self
            : SELF_TYPE
            foo (
            )
          : String
        : Object
      : Object
    _line_num: 6
    _method
      foo (
      )
      : String
      _line_num: 6
      _string
        "test"
      : String
    )
