_line_num: 1
_program
  _line_num: 1
  _class
    A
    _inherits: Object
    _file_name: "inheritsObject.test"
    (
    _line_num: 3
    _attr
      foo
      : Int
      _line_num: 3
      _no_expr
      : Int
    _line_num: 5
    _method
      main (
      )
      : Int
      _line_num: 6
      _int
        6
      : Int
    )
  _line_num: 11
  _class
    B
    _inherits: Object
    _file_name: "inheritsObject.test"
    (
    _line_num: 13
    _attr
      bar
      : Int
      _line_num: 13
      _no_expr
      : Int
    )
  _line_num: 17
  _class
    Main
    _inherits: Object
    _file_name: "inheritsObject.test"
    (
    _line_num: 17
    _method
      main (
      )
      : Int
      _line_num: 17
      _int
        6
      : Int
    )
