_line_num: 1
_program
  _line_num: 1
  _class
    Main
    _inherits: IO
    _file_name: "initwithself.test"
    (
    _line_num: 2
    _attr
      x
      : Main
      _line_num: 2
      _object
        self
      : SELF_TYPE
    _line_num: 3
    _method
      main (
      )
      : Object
      _line_num: 3
      _block
        _line_num: 4
        _object
          self
        : SELF_TYPE
      : SELF_TYPE
    )
