_line_num: 1
_program
  _line_num: 1
  _class
    Main
    _inherits: IO
    _file_name: "io.test"
    (
    _line_num: 2
    _attr
      x
      : Int
      _line_num: 2
      _no_expr
      : Int
    _line_num: 3
    _attr
      y
      : String
      _line_num: 3
      _no_expr
      : String
    _line_num: 4
    _method
      main (
      )
      : Object
      _line_num: 4
      _block
        _line_num: 5
        _dispatch
          _is_tail: false
          _line_num: 5
          _object
            self
          : SELF_TYPE
          out_string (
          _line_num: 5
          _string
            "test"
          : String
          )
        : SELF_TYPE
        _line_num: 6
        _dispatch
          _is_tail: false
          _line_num: 6
          _object
            self
          : SELF_TYPE
          out_int (
          _line_num: 6
          _int
            5
          : Int
          )
        : SELF_TYPE
        _line_num: 7
        _assign
          y
          _line_num: 7
          _dispatch
            _is_tail: false
            _line_num: 7
            _object
              self
            : SELF_TYPE
            in_string (
            )
          : String
        : String
        _line_num: 8
        _assign
          x
          _line_num: 8
          _dispatch
            _is_tail: false
            _line_num: 8
            _object
              self
            : SELF_TYPE
            in_int (
            )
          : Int
        : Int
      : Int
    )
