_line_num: 1
_program
  _line_num: 1
  _class
    Main
    _inherits: IO
    _file_name: "isvoid.test"
    (
    _line_num: 2
    _attr
      x
      : Bool
      _line_num: 2
      _no_expr
      : Bool
    _line_num: 3
    _method
      main (
      )
      : Object
      _line_num: 3
      _block
        _line_num: 4
        _isvoid
          _line_num: 4
          _bool
            true
          : Bool
        : Bool
        _line_num: 4
        _isvoid
          _line_num: 4
          _bool
            false
          : Bool
        : Bool
        _line_num: 4
        _isvoid
          _line_num: 4
          _object
            x
          : Bool
        : Bool
      : Bool
    )
