_line_num: 1
_program
  _line_num: 1
  _class
    Main
    _inherits: Object
    _file_name: "iteratedlet.test"
    (
    _line_num: 2
    _method
      main (
      )
      : Int
      _line_num: 4
      _let
        x
        Int
        _line_num: 4
        _int
          42
        : Int
        _line_num: 5
        _let
          y
          String
          _line_num: 5
          _string
            "foo"
          : String
          _line_num: 6
          _let
            z
            SELF_TYPE
            _line_num: 6
            _object
              self
            : SELF_TYPE
            _line_num: 8
            _object
              x
            : Int
          : Int
        : Int
      : Int
    )
