#1
_program
  #1
  _class
    Main
    Object
    "iteratedlet.test"
    (
    #2
    _method
      main
      Int
      #4
      _let
        x
        Int
        #4
        _int
          42
        : Int
        #5
        _let
          y
          String
          #5
          _string
            "foo"
          : String
          #6
          _let
            z
            SELF_TYPE
            #6
            _object
              self
            : SELF_TYPE
            #8
            _object
              x
            : Int
          : Int
        : Int
      : Int
    )
