_line_num: 1
_program
  _line_num: 1
  _class
    Main
    _inherits: IO
    _file_name: "letnoinit.test"
    (
    _line_num: 2
    _method
      main (
      )
      : Object
      _line_num: 2
      _block
        _line_num: 3
        _let
          x
          : Int
          _line_num: 3
          _no_expr
          : Int
          _line_num: 3
          _object
            x
          : Int
        : Int
      : Int
    )
