_line_num: 1
_program
  _line_num: 1
  _class
    Main
    _inherits: IO
    _file_name: "letshadows.test"
    (
    _line_num: 2
    _attr
      x
      : Int
      _line_num: 2
      _no_expr
      : Int
    _line_num: 3
    _method
      main (
      )
      : Object
      _line_num: 3
      _block
        _line_num: 4
        _let
          x
          String
          _line_num: 4
          _string
            "test"
          : String
          _line_num: 4
          _dispatch
            _is_tail: true
            _line_num: 4
            _object
              x
            : String
            length (
            )
          : Int
        : Int
      : Int
    )
