_line_num: 1
_program
  _line_num: 1
  _class
    Main
    _inherits: IO
    _file_name: "letselftype.test"
    (
    _line_num: 2
    _method
      main (
      )
      : Object
      _line_num: 2
      _block
        _line_num: 3
        _let
          y
          : SELF_TYPE
          _line_num: 4
          _let
            x
            : SELF_TYPE
            _line_num: 4
            _no_expr
            : SELF_TYPE
            _line_num: 4
            _object
              x
            : SELF_TYPE
          : SELF_TYPE
          _line_num: 5
          _object
            y
          : SELF_TYPE
        : SELF_TYPE
      : SELF_TYPE
    )
