_line_num: 26
_program
  _line_num: 26
  _class
    List
    _inherits: Object
    _file_name: "list.cl.test"
    (
    _line_num: 29
    _method
      isNil (
      )
      : Bool
      _line_num: 29
      _bool
        true
      : Bool
    _line_num: 35
    _method
      head (
      )
      : Int
      _line_num: 35
      _block
        _line_num: 35
        _dispatch
          _is_tail: false
          _line_num: 35
          _object
            self
          : SELF_TYPE
          abort (
          )
        : Object
        _line_num: 35
        _int
          0
        : Int
      : Int
    _line_num: 40
    _method
      tail (
      )
      : List
      _line_num: 40
      _block
        _line_num: 40
        _dispatch
          _is_tail: false
          _line_num: 40
          _object
            self
          : SELF_TYPE
          abort (
          )
        : Object
        _line_num: 40
        _object
          self
        : SELF_TYPE
      : SELF_TYPE
    _line_num: 49
    _method
      cons (
      _line_num: 49
      _formal
        i
        Int
      )
      : List
      _line_num: 50
      _dispatch
        _is_tail: true
        _line_num: 50
        _new
          Cons
        : Cons
        init (
        _line_num: 50
        _object
          i
        : Int
        _line_num: 50
        _object
          self
        : SELF_TYPE
        )
      : List
    )
  _line_num: 70
  _class
    Cons
    _inherits: List
    _file_name: "list.cl.test"
    (
    _line_num: 72
    _attr
      car
      : Int
      _line_num: 72
      _no_expr
      : Int
    _line_num: 74
    _attr
      cdr
      : List
      _line_num: 74
      _no_expr
      : List
    _line_num: 76
    _method
      isNil (
      )
      : Bool
      _line_num: 76
      _bool
        false
      : Bool
    _line_num: 78
    _method
      head (
      )
      : Int
      _line_num: 78
      _object
        car
      : Int
    _line_num: 80
    _method
      tail (
      )
      : List
      _line_num: 80
      _object
        cdr
      : List
    _line_num: 82
    _method
      init (
      _line_num: 82
      _formal
        i
        Int
      _line_num: 82
      _formal
        rest
        List
      )
      : List
      _line_num: 83
      _block
        _line_num: 84
        _assign
          car
          _line_num: 84
          _object
            i
          : Int
        : Int
        _line_num: 85
        _assign
          cdr
          _line_num: 85
          _object
            rest
          : List
        : List
        _line_num: 86
        _object
          self
        : SELF_TYPE
      : SELF_TYPE
    )
  _line_num: 100
  _class
    Main
    _inherits: IO
    _file_name: "list.cl.test"
    (
    _line_num: 102
    _attr
      mylist
      : List
      _line_num: 102
      _no_expr
      : List
    _line_num: 107
    _method
      print_list (
      _line_num: 107
      _formal
        l
        List
      )
      : Object
      _line_num: 108
      _cond
        _line_num: 108
        _dispatch
          _is_tail: false
          _line_num: 108
          _object
            l
          : List
          isNil (
          )
        : Bool
        _line_num: 108
        _dispatch
          _is_tail: true
          _line_num: 108
          _object
            self
          : SELF_TYPE
          out_string (
          _line_num: 108
          _string
            "\n"
          : String
          )
        : SELF_TYPE
        _line_num: 109
        _block
          _line_num: 110
          _dispatch
            _is_tail: false
            _line_num: 110
            _object
              self
            : SELF_TYPE
            out_int (
            _line_num: 110
            _dispatch
              _is_tail: false
              _line_num: 110
              _object
                l
              : List
              head (
              )
            : Int
            )
          : SELF_TYPE
          _line_num: 111
          _dispatch
            _is_tail: false
            _line_num: 111
            _object
              self
            : SELF_TYPE
            out_string (
            _line_num: 111
            _string
              " "
            : String
            )
          : SELF_TYPE
          _line_num: 112
          _dispatch
            _is_tail: true
            _line_num: 112
            _object
              self
            : SELF_TYPE
            print_list (
            _line_num: 112
            _dispatch
              _is_tail: false
              _line_num: 112
              _object
                l
              : List
              tail (
              )
            : List
            )
          : Object
        : Object
      : Object
    _line_num: 126
    _method
      main (
      )
      : Object
      _line_num: 127
      _block
        _line_num: 128
        _assign
          mylist
          _line_num: 128
          _dispatch
            _is_tail: false
            _line_num: 128
            _dispatch
              _is_tail: false
              _line_num: 128
              _dispatch
                _is_tail: false
                _line_num: 128
                _dispatch
                  _is_tail: false
                  _line_num: 128
                  _dispatch
                    _is_tail: false
                    _line_num: 128
                    _new
                      List
                    : List
                    cons (
                    _line_num: 128
                    _int
                      1
                    : Int
                    )
                  : List
                  cons (
                  _line_num: 128
                  _int
                    2
                  : Int
                  )
                : List
                cons (
                _line_num: 128
                _int
                  3
                : Int
                )
              : List
              cons (
              _line_num: 128
              _int
                4
              : Int
              )
            : List
            cons (
            _line_num: 128
            _int
              5
            : Int
            )
          : List
        : List
        _line_num: 129
        _loop
          _line_num: 129
          _comp
            _line_num: 129
            _dispatch
              _is_tail: false
              _line_num: 129
              _object
                mylist
              : List
              isNil (
              )
            : Bool
          : Bool
          _line_num: 130
          _block
            _line_num: 131
            _dispatch
              _is_tail: false
              _line_num: 131
              _object
                self
              : SELF_TYPE
              print_list (
              _line_num: 131
              _object
                mylist
              : List
              )
            : Object
            _line_num: 132
            _assign
              mylist
              _line_num: 132
              _dispatch
                _is_tail: false
                _line_num: 132
                _object
                  mylist
                : List
                tail (
                )
              : List
            : List
          : List
        : Object
      : Object
    )
