_line_num: 1
_program
  _line_num: 1
  _class
    Main
    _inherits: Object
    _file_name: "methodcallsitself.test"
    (
    _line_num: 1
    _method
      main (
      )
      : Int
      _line_num: 1
      _int
        0
      : Int
    )
  _line_num: 3
  _class
    A
    _inherits: Object
    _file_name: "methodcallsitself.test"
    (
    _line_num: 4
    _method
      f (
      )
      : Int
      _line_num: 4
      _dispatch
        _is_tail: true
        _line_num: 4
        _object
          self
        : SELF_TYPE
        f (
        )
      : Int
    _line_num: 5
    _method
      g (
      _line_num: 5
      _formal
        a
        Int
      )
      : Int
      _line_num: 5
      _dispatch
        _is_tail: true
        _line_num: 5
        _object
          self
        : SELF_TYPE
        g (
        _line_num: 5
        _dispatch
          _is_tail: false
          _line_num: 5
          _object
            self
          : SELF_TYPE
          g (
          _line_num: 5
          _dispatch
            _is_tail: false
            _line_num: 5
            _object
              self
            : SELF_TYPE
            f (
            )
          : Int
          )
        : Int
        )
      : Int
    _line_num: 6
    _method
      h (
      _line_num: 6
      _formal
        a
        Int
      _line_num: 6
      _formal
        b
        Int
      )
      : Int
      _line_num: 6
      _dispatch
        _is_tail: true
        _line_num: 6
        _object
          self
        : SELF_TYPE
        h (
        _line_num: 6
        _dispatch
          _is_tail: false
          _line_num: 6
          _object
            self
          : SELF_TYPE
          h (
          _line_num: 6
          _int
            0
          : Int
          _line_num: 6
          _int
            0
          : Int
          )
        : Int
        _line_num: 6
        _dispatch
          _is_tail: false
          _line_num: 6
          _object
            self
          : SELF_TYPE
          h (
          _line_num: 6
          _dispatch
            _is_tail: false
            _line_num: 6
            _object
              self
            : SELF_TYPE
            f (
            )
          : Int
          _line_num: 6
          _dispatch
            _is_tail: false
            _line_num: 6
            _object
              self
            : SELF_TYPE
            f (
            )
          : Int
          )
        : Int
        )
      : Int
    )
