_line_num: 1
_program
  _line_num: 1
  _class
    A
    _inherits: Object
    _file_name: "methodnameclash.test"
    (
    _line_num: 1
    _attr
      x
      : Int
      _line_num: 1
      _no_expr
      : Int
    _line_num: 1
    _attr
      y
      : String
      _line_num: 1
      _no_expr
      : String
    )
  _line_num: 3
  _class
    L
    _inherits: A
    _file_name: "methodnameclash.test"
    (
    _line_num: 3
    _method
      foo (
      )
      : Int
      _line_num: 3
      _object
        x
      : Int
    )
  _line_num: 4
  _class
    R
    _inherits: A
    _file_name: "methodnameclash.test"
    (
    _line_num: 4
    _method
      foo (
      )
      : String
      _line_num: 4
      _object
        y
      : String
    )
  _line_num: 6
  _class
    Main
    _inherits: Object
    _file_name: "methodnameclash.test"
    (
    _line_num: 6
    _method
      main (
      )
      : Int
      _line_num: 6
      _dispatch
        _is_tail: true
        _line_num: 6
        _new
          L
        : L
        foo (
        )
      : Int
    )
