_line_num: 1
_program
  _line_num: 1
  _class
    Main
    _inherits: IO
    _file_name: "neg.test"
    (
    _line_num: 2
    _attr
      x
      : Bool
      _line_num: 2
      _no_expr
      : Bool
    _line_num: 3
    _method
      main (
      )
      : Object
      _line_num: 3
      _block
        _line_num: 4
        _neg
          _line_num: 4
          _int
            7
          : Int
        : Int
        _line_num: 4
        _neg
          _line_num: 4
          _dispatch
            _is_tail: false
            _line_num: 4
            _object
              self
            : SELF_TYPE
            foo (
            )
          : Int
        : Int
      : Int
    _line_num: 6
    _method
      foo (
      )
      : Int
      _line_num: 6
      _int
        4
      : Int
    )
