_line_num: 1
_program
  _line_num: 1
  _class
    A
    _inherits: Object
    _file_name: "newselftype.test"
    (
    _line_num: 3
    _attr
      bar
      : Int
      _line_num: 3
      _dispatch
        _is_tail: false
        _line_num: 3
        _object
          self
        : SELF_TYPE
        foo (
        _line_num: 3
        _new
          SELF_TYPE
        : SELF_TYPE
        )
      : Int
    _line_num: 5
    _method
      foo (
      _line_num: 5
      _formal
        a
        A
      )
      : Int
      _line_num: 5
      _neg
        _line_num: 5
        _int
          7
        : Int
      : Int
    )
  _line_num: 8
  _class
    Main
    _inherits: Object
    _file_name: "newselftype.test"
    (
    _line_num: 8
    _method
      main (
      )
      : Int
      _line_num: 8
      _int
        6
      : Int
    )
