_line_num: 1
_program
  _line_num: 1
  _class
    A
    _inherits: Object
    _file_name: "objectdispatchabort.test"
    (
    _line_num: 3
    _method
      foo (
      )
      : Object
      _line_num: 3
      _dispatch
        _is_tail: true
        _line_num: 3
        _new
          Object
        : Object
        abort (
        )
      : Object
    )
  _line_num: 6
  _class
    Main
    _inherits: Object
    _file_name: "objectdispatchabort.test"
    (
    _line_num: 6
    _method
      main (
      )
      : Int
      _line_num: 6
      _int
        6
      : Int
    )
