_line_num: 1
_program
  _line_num: 1
  _class
    Main
    _inherits: Object
    _file_name: "overridingmethod3.test"
    (
    _line_num: 1
    _method
      main (
      )
      : Int
      _line_num: 1
      _int
        0
      : Int
    )
  _line_num: 3
  _class
    A
    _inherits: Object
    _file_name: "overridingmethod3.test"
    (
    _line_num: 4
    _method
      inky (
      )
      : SELF_TYPE
      _line_num: 4
      _object
        self
      : SELF_TYPE
    )
  _line_num: 7
  _class
    B
    _inherits: A
    _file_name: "overridingmethod3.test"
    (
    _line_num: 8
    _method
      inky (
      )
      : SELF_TYPE
      _line_num: 8
      _new
        SELF_TYPE
      : SELF_TYPE
    )
