_line_num: 1
_program
  _line_num: 1
  _class
    A
    _inherits: Object
    _file_name: "overridingmethod.test"
    (
    _line_num: 3
    _method
      foo (
      )
      : Int
      _line_num: 3
      _int
        6
      : Int
    )
  _line_num: 7
  _class
    B
    _inherits: A
    _file_name: "overridingmethod.test"
    (
    _line_num: 9
    _method
      foo (
      )
      : Int
      _line_num: 9
      _int
        7
      : Int
    )
  _line_num: 12
  _class
    Main
    _inherits: Object
    _file_name: "overridingmethod.test"
    (
    _line_num: 12
    _method
      main (
      )
      : Int
      _line_num: 12
      _int
        6
      : Int
    )
