_line_num: 1
_program
  _line_num: 1
  _class
    Main
    _inherits: Object
    _file_name: "overridingmethod2.test"
    (
    _line_num: 1
    _method
      main (
      )
      : Int
      _line_num: 1
      _int
        0
      : Int
    )
  _line_num: 3
  _class
    A
    _inherits: Object
    _file_name: "overridingmethod2.test"
    (
    _line_num: 4
    _method
      inky (
      _line_num: 4
      _formal
        a
        : Int
      _line_num: 4
      _formal
        b
        : String
      _line_num: 4
      _formal
        c
        : A
      _line_num: 4
      _formal
        d
        : Bool
      )
      : Int
      _line_num: 4
      _object
        a
      : Int
    )
  _line_num: 7
  _class
    B
    _inherits: A
    _file_name: "overridingmethod2.test"
    (
    _line_num: 8
    _method
      inky (
      _line_num: 8
      _formal
        a
        : Int
      _line_num: 8
      _formal
        b
        : String
      _line_num: 8
      _formal
        c
        : A
      _line_num: 8
      _formal
        d
        : Bool
      )
      : Int
      _line_num: 8
      _plus
        _line_num: 8
        _object
          a
        : Int
        _line_num: 8
        _int
          1
        : Int
      : Int
    )
