_line_num: 1
_program
  _line_num: 1
  _class
    Main
    _inherits: Object
    _file_name: "overriderenamearg.test"
    (
    _line_num: 1
    _method
      main (
      )
      : Int
      _line_num: 1
      _int
        0
      : Int
    )
  _line_num: 3
  _class
    D
    _inherits: Object
    _file_name: "overriderenamearg.test"
    (
    _line_num: 4
    _method
      inky (
      _line_num: 4
      _formal
        b
        Int
      )
      : Object
      _line_num: 4
      _int
        1
      : Int
    )
  _line_num: 7
  _class
    E
    _inherits: D
    _file_name: "overriderenamearg.test"
    (
    _line_num: 8
    _method
      inky (
      _line_num: 8
      _formal
        c
        Int
      )
      : Object
      _line_num: 8
      _int
        1
      : Int
    )
