_line_num: 1
_program
  _line_num: 1
  _class
    Main
    _inherits: Object
    _file_name: "scopes.test"
    (
    _line_num: 1
    _method
      main (
      )
      : Int
      _line_num: 1
      _int
        0
      : Int
    )
  _line_num: 3
  _class
    A
    _inherits: Object
    _file_name: "scopes.test"
    (
    _line_num: 4
    _attr
      x
      : Int
      _line_num: 4
      _no_expr
      : Int
    _line_num: 6
    _method
      f (
      _line_num: 6
      _formal
        x
        A
      )
      : String
      _line_num: 6
      _string
        "ab"
      : String
    _line_num: 7
    _method
      g (
      _line_num: 7
      _formal
        x
        Bool
      )
      : A
      _line_num: 7
      _object
        self
      : SELF_TYPE
    _line_num: 8
    _method
      h (
      )
      : Object
      _line_num: 8
      _let
        x
        String
        _line_num: 8
        _dispatch
          _is_tail: false
          _line_num: 8
          _object
            self
          : SELF_TYPE
          f (
          _line_num: 8
          _let
            x
            Bool
            _line_num: 8
            _no_expr
            : Bool
            _line_num: 8
            _dispatch
              _is_tail: false
              _line_num: 8
              _object
                self
              : SELF_TYPE
              g (
              _line_num: 8
              _object
                x
              : Bool
              )
            : A
          : A
          )
        : String
        _line_num: 8
        _assign
          x
          _line_num: 8
          _string
            "ab"
          : String
        : String
      : String
    )
