_line_num: 1
_program
  _line_num: 1
  _class
    Main
    _inherits: Object
    _file_name: "simplecase.test"
    (
    _line_num: 1
    _method
      main (
      )
      : Int
      _line_num: 1
      _int
        0
      : Int
    )
  _line_num: 3
  _class
    A
    _inherits: Object
    _file_name: "simplecase.test"
    (
    _line_num: 4
    _attr
      moo
      : Object
      _line_num: 4
      _no_expr
      : Object
    _line_num: 5
    _method
      boo (
      )
      : Object
      _line_num: 5
      _block
        _line_num: 5
        _typcase
          _line_num: 5
          _object
            moo
          : Object
          _line_num: 5
          _branch
            i
            : Int
            _line_num: 5
            _object
              i
            : Int
          _line_num: 6
          _branch
            b
            : Bool
            _line_num: 6
            _object
              b
            : Bool
          _line_num: 7
          _branch
            s
            : String
            _line_num: 7
            _object
              s
            : String
        : Object
      : Object
    )
