_line_num: 1
_program
  _line_num: 1
  _class
    Main
    _inherits: Object
    _file_name: "simplearith.test"
    (
    _line_num: 2
    _method
      main (
      )
      : Object
      _line_num: 2
      _block
        _line_num: 2
        _plus
          _line_num: 2
          _int
            5
          : Int
          _line_num: 2
          _int
            4
          : Int
        : Int
        _line_num: 2
        _sub
          _line_num: 2
          _int
            5
          : Int
          _line_num: 2
          _int
            4
          : Int
        : Int
        _line_num: 2
        _mul
          _line_num: 2
          _int
            3
          : Int
          _line_num: 2
          _int
            2
          : Int
        : Int
        _line_num: 2
        _divide
          _line_num: 2
          _int
            3
          : Int
          _line_num: 2
          _int
            2
          : Int
        : Int
      : Int
    )
