_line_num: 1
_program
  _line_num: 1
  _class
    Main
    _inherits: Object
    _file_name: "staticdispatch.test"
    (
    _line_num: 2
    _attr
      b
      : B
      _line_num: 2
      _new
        B
      : B
    _line_num: 3
    _method
      main (
      )
      : Object
      _line_num: 3
      _static_dispatch
        _is_tail: true
        _line_num: 3
        _object
          b
        : B
        A
        foo (
        _line_num: 3
        _int
          5
        : Int
        _line_num: 3
        _object
          b
        : B
        _line_num: 3
        _object
          b
        : B
        _line_num: 3
        _object
          b
        : B
        )
      : Int
    )
  _line_num: 6
  _class
    A
    _inherits: Object
    _file_name: "staticdispatch.test"
    (
    _line_num: 7
    _method
      foo (
      _line_num: 7
      _formal
        a
        Int
      _line_num: 7
      _formal
        b
        B
      _line_num: 7
      _formal
        c
        A
      _line_num: 7
      _formal
        d
        B
      )
      : Int
      _line_num: 8
      _int
        5
      : Int
    )
  _line_num: 13
  _class
    B
    _inherits: A
    _file_name: "staticdispatch.test"
    (
    _line_num: 15
    _method
      foo (
      _line_num: 15
      _formal
        a
        Int
      _line_num: 15
      _formal
        b
        B
      _line_num: 15
      _formal
        c
        A
      _line_num: 15
      _formal
        d
        B
      )
      : Int
      _line_num: 16
      _int
        6
      : Int
    )
