_line_num: 1
_program
  _line_num: 1
  _class
    Main
    _inherits: Object
    _file_name: "stringtest.test"
    (
    _line_num: 2
    _method
      main (
      )
      : Object
      _line_num: 2
      _block
        _line_num: 3
        _dispatch
          _is_tail: false
          _line_num: 3
          _string
            "test"
          : String
          length (
          )
        : Int
        _line_num: 4
        _dispatch
          _is_tail: false
          _line_num: 4
          _string
            "test"
          : String
          substr (
          _line_num: 4
          _int
            0
          : Int
          _line_num: 4
          _int
            1
          : Int
          )
        : String
        _line_num: 5
        _dispatch
          _is_tail: true
          _line_num: 5
          _string
            "test"
          : String
          concat (
          _line_num: 5
          _string
            " me"
          : String
          )
        : String
      : String
    )
