_line_num: 1
_program
  _line_num: 1
  _class
    A
    _inherits: Object
    _file_name: "subtypemethodreturn.test"
    (
    _line_num: 2
    _method
      foo (
      )
      : A
      _line_num: 3
      _let
        x
        A
        _line_num: 3
        _no_expr
        : A
        _line_num: 3
        _block
          _line_num: 4
          _assign
            x
            _line_num: 4
            _new
              A
            : A
          : A
          _line_num: 5
          _dispatch
            _is_tail: true
            _line_num: 5
            _object
              x
            : A
            foo (
            )
          : A
        : A
      : A
    )
  _line_num: 11
  _class
    B
    _inherits: A
    _file_name: "subtypemethodreturn.test"
    (
    _line_num: 13
    _method
      foo (
      )
      : A
      _line_num: 14
      _object
        self
      : SELF_TYPE
    )
  _line_num: 19
  _class
    Main
    _inherits: Object
    _file_name: "subtypemethodreturn.test"
    (
    _line_num: 19
    _method
      main (
      )
      : Int
      _line_num: 19
      _int
        6
      : Int
    )
