_line_num: 1
_program
  _line_num: 1
  _class
    Main
    _inherits: Object
    _file_name: "trickyatdispatch.test"
    (
    _line_num: 1
    _method
      main (
      )
      : Int
      _line_num: 1
      _int
        0
      : Int
    )
  _line_num: 3
  _class
    A
    _inherits: Object
    _file_name: "trickyatdispatch.test"
    (
    _line_num: 4
    _method
      inky (
      )
      : Int
      _line_num: 4
      _int
        1
      : Int
    )
  _line_num: 7
  _class
    B
    _inherits: A
    _file_name: "trickyatdispatch.test"
    (
    _line_num: 8
    _method
      binky (
      )
      : String
      _line_num: 8
      _string
        "hello"
      : String
    )
  _line_num: 11
  _class
    C
    _inherits: Object
    _file_name: "trickyatdispatch.test"
    (
    _line_num: 12
    _attr
      b
      : B
      _line_num: 12
      _no_expr
      : B
    _line_num: 13
    _method
      winky (
      )
      : Int
      _line_num: 13
      _static_dispatch
        _is_tail: true
        _line_num: 13
        _object
          b
        : B
        B
        inky (
        )
      : Int
    )
