_line_num: 1
_program
  _line_num: 1
  _class
    A
    _inherits: Object
    _file_name: "arithprecedence.test"
    (
    _line_num: 2
    _method
      f (
      )
      : Int
      _line_num: 2
      _block
        _line_num: 3
        _sub
          _line_num: 3
          _plus
            _line_num: 3
            _object
              a
            : _no_type
            _line_num: 3
            _object
              b
            : _no_type
          : _no_type
          _line_num: 3
          _object
            c
          : _no_type
        : _no_type
        _line_num: 4
        _plus
          _line_num: 4
          _sub
            _line_num: 4
            _object
              a
            : _no_type
            _line_num: 4
            _object
              b
            : _no_type
          : _no_type
          _line_num: 4
          _object
            c
          : _no_type
        : _no_type
        _line_num: 6
        _plus
          _line_num: 6
          _object
            a
          : _no_type
          _line_num: 6
          _mul
            _line_num: 6
            _object
              b
            : _no_type
            _line_num: 6
            _object
              c
            : _no_type
          : _no_type
        : _no_type
        _line_num: 7
        _plus
          _line_num: 7
          _mul
            _line_num: 7
            _object
              a
            : _no_type
            _line_num: 7
            _object
              b
            : _no_type
          : _no_type
          _line_num: 7
          _object
            c
          : _no_type
        : _no_type
        _line_num: 9
        _plus
          _line_num: 9
          _object
            a
          : _no_type
          _line_num: 9
          _divide
            _line_num: 9
            _object
              b
            : _no_type
            _line_num: 9
            _object
              c
            : _no_type
          : _no_type
        : _no_type
        _line_num: 10
        _plus
          _line_num: 10
          _divide
            _line_num: 10
            _object
              a
            : _no_type
            _line_num: 10
            _object
              b
            : _no_type
          : _no_type
          _line_num: 10
          _object
            c
          : _no_type
        : _no_type
        _line_num: 12
        _sub
          _line_num: 12
          _object
            a
          : _no_type
          _line_num: 12
          _mul
            _line_num: 12
            _object
              b
            : _no_type
            _line_num: 12
            _object
              c
            : _no_type
          : _no_type
        : _no_type
        _line_num: 13
        _sub
          _line_num: 13
          _mul
            _line_num: 13
            _object
              a
            : _no_type
            _line_num: 13
            _object
              b
            : _no_type
          : _no_type
          _line_num: 13
          _object
            c
          : _no_type
        : _no_type
        _line_num: 15
        _sub
          _line_num: 15
          _object
            a
          : _no_type
          _line_num: 15
          _divide
            _line_num: 15
            _object
              b
            : _no_type
            _line_num: 15
            _object
              c
            : _no_type
          : _no_type
        : _no_type
        _line_num: 16
        _sub
          _line_num: 16
          _divide
            _line_num: 16
            _object
              a
            : _no_type
            _line_num: 16
            _object
              b
            : _no_type
          : _no_type
          _line_num: 16
          _object
            c
          : _no_type
        : _no_type
        _line_num: 18
        _divide
          _line_num: 18
          _mul
            _line_num: 18
            _object
              a
            : _no_type
            _line_num: 18
            _object
              b
            : _no_type
          : _no_type
          _line_num: 18
          _object
            c
          : _no_type
        : _no_type
        _line_num: 19
        _mul
          _line_num: 19
          _divide
            _line_num: 19
            _object
              a
            : _no_type
            _line_num: 19
            _object
              b
            : _no_type
          : _no_type
          _line_num: 19
          _object
            c
          : _no_type
        : _no_type
      : _no_type
    )
