_line_num: 1
_program
  _line_num: 1
  _class
    Main
    _inherits: Object
    _file_name: "assignseq.test"
    (
    _line_num: 2
    _attr
      x
      : Int
      _line_num: 2
      _no_expr
      : _no_type
    _line_num: 3
    _attr
      y
      : Int
      _line_num: 3
      _no_expr
      : _no_type
    _line_num: 4
    _method
      main (
      )
      : Object
      _line_num: 4
      _block
        _line_num: 4
        _assign
          x
          _line_num: 4
          _assign
            y
            _line_num: 4
            _neg
              _line_num: 4
              _int
                5
              : _no_type
            : _no_type
          : _no_type
        : _no_type
      : _no_type
    )
