_line_num: 1
_program
  _line_num: 1
  _class
    Test
    _inherits: Object
    _file_name: "assignment.test"
    (
    _line_num: 2
    _attr
      foo
      : Int
      _line_num: 2
      _no_expr
      : _no_type
    _line_num: 3
    _method
      bar (
      )
      : Object
      _line_num: 3
      _assign
        foo
        _line_num: 3
        _int
          3
        : _no_type
      : _no_type
    )
