_line_num: 1
_program
  _line_num: 1
  _class
    Hello
    _inherits: Object
    _file_name: "associativity-times.test"
    (
    _line_num: 2
    _attr
      foo
      : Int
      _line_num: 2
      _no_expr
      : _no_type
    _line_num: 4
    _method
      moo2 (
      _line_num: 4
      _formal
        a
        String
      _line_num: 4
      _formal
        b
        Int
      _line_num: 4
      _formal
        c
        Int
      _line_num: 4
      _formal
        d
        Int
      )
      : Hello
      _line_num: 5
      _mul
        _line_num: 5
        _mul
          _line_num: 5
          _mul
            _line_num: 5
            _object
              a
            : _no_type
            _line_num: 5
            _object
              b
            : _no_type
          : _no_type
          _line_num: 5
          _object
            c
          : _no_type
        : _no_type
        _line_num: 5
        _object
          d
        : _no_type
      : _no_type
    )
