_line_num: 13
_program
  _line_num: 13
  _class
    A2I
    _inherits: Object
    _file_name: "atoi.test"
    (
    _line_num: 15
    _method
      c2i (
      _line_num: 15
      _formal
        char
        : String
      )
      : Int
      _line_num: 16
      _cond
        _line_num: 16
        _eq
          _line_num: 16
          _object
            char
          : _no_type
          _line_num: 16
          _string
            "0"
          : _no_type
        : _no_type
        _line_num: 16
        _int
          0
        : _no_type
        _line_num: 17
        _cond
          _line_num: 17
          _eq
            _line_num: 17
            _object
              char
            : _no_type
            _line_num: 17
            _string
              "1"
            : _no_type
          : _no_type
          _line_num: 17
          _int
            1
          : _no_type
          _line_num: 18
          _cond
            _line_num: 18
            _eq
              _line_num: 18
              _object
                char
              : _no_type
              _line_num: 18
              _string
                "2"
              : _no_type
            : _no_type
            _line_num: 18
            _int
              2
            : _no_type
            _line_num: 19
            _cond
              _line_num: 19
              _eq
                _line_num: 19
                _object
                  char
                : _no_type
                _line_num: 19
                _string
                  "3"
                : _no_type
              : _no_type
              _line_num: 19
              _int
                3
              : _no_type
              _line_num: 20
              _cond
                _line_num: 20
                _eq
                  _line_num: 20
                  _object
                    char
                  : _no_type
                  _line_num: 20
                  _string
                    "4"
                  : _no_type
                : _no_type
                _line_num: 20
                _int
                  4
                : _no_type
                _line_num: 21
                _cond
                  _line_num: 21
                  _eq
                    _line_num: 21
                    _object
                      char
                    : _no_type
                    _line_num: 21
                    _string
                      "5"
                    : _no_type
                  : _no_type
                  _line_num: 21
                  _int
                    5
                  : _no_type
                  _line_num: 22
                  _cond
                    _line_num: 22
                    _eq
                      _line_num: 22
                      _object
                        char
                      : _no_type
                      _line_num: 22
                      _string
                        "6"
                      : _no_type
                    : _no_type
                    _line_num: 22
                    _int
                      6
                    : _no_type
                    _line_num: 23
                    _cond
                      _line_num: 23
                      _eq
                        _line_num: 23
                        _object
                          char
                        : _no_type
                        _line_num: 23
                        _string
                          "7"
                        : _no_type
                      : _no_type
                      _line_num: 23
                      _int
                        7
                      : _no_type
                      _line_num: 24
                      _cond
                        _line_num: 24
                        _eq
                          _line_num: 24
                          _object
                            char
                          : _no_type
                          _line_num: 24
                          _string
                            "8"
                          : _no_type
                        : _no_type
                        _line_num: 24
                        _int
                          8
                        : _no_type
                        _line_num: 25
                        _cond
                          _line_num: 25
                          _eq
                            _line_num: 25
                            _object
                              char
                            : _no_type
                            _line_num: 25
                            _string
                              "9"
                            : _no_type
                          : _no_type
                          _line_num: 25
                          _int
                            9
                          : _no_type
                          _line_num: 26
                          _block
                            _line_num: 26
                            _dispatch
                              _is_tail: false
                              _line_num: 26
                              _object
                                self
                              : _no_type
                              abort (
                              )
                            : _no_type
                            _line_num: 26
                            _int
                              0
                            : _no_type
                          : _no_type
                        : _no_type
                      : _no_type
                    : _no_type
                  : _no_type
                : _no_type
              : _no_type
            : _no_type
          : _no_type
        : _no_type
      : _no_type
    _line_num: 33
    _method
      i2c (
      _line_num: 33
      _formal
        i
        : Int
      )
      : String
      _line_num: 34
      _cond
        _line_num: 34
        _eq
          _line_num: 34
          _object
            i
          : _no_type
          _line_num: 34
          _int
            0
          : _no_type
        : _no_type
        _line_num: 34
        _string
          "0"
        : _no_type
        _line_num: 35
        _cond
          _line_num: 35
          _eq
            _line_num: 35
            _object
              i
            : _no_type
            _line_num: 35
            _int
              1
            : _no_type
          : _no_type
          _line_num: 35
          _string
            "1"
          : _no_type
          _line_num: 36
          _cond
            _line_num: 36
            _eq
              _line_num: 36
              _object
                i
              : _no_type
              _line_num: 36
              _int
                2
              : _no_type
            : _no_type
            _line_num: 36
            _string
              "2"
            : _no_type
            _line_num: 37
            _cond
              _line_num: 37
              _eq
                _line_num: 37
                _object
                  i
                : _no_type
                _line_num: 37
                _int
                  3
                : _no_type
              : _no_type
              _line_num: 37
              _string
                "3"
              : _no_type
              _line_num: 38
              _cond
                _line_num: 38
                _eq
                  _line_num: 38
                  _object
                    i
                  : _no_type
                  _line_num: 38
                  _int
                    4
                  : _no_type
                : _no_type
                _line_num: 38
                _string
                  "4"
                : _no_type
                _line_num: 39
                _cond
                  _line_num: 39
                  _eq
                    _line_num: 39
                    _object
                      i
                    : _no_type
                    _line_num: 39
                    _int
                      5
                    : _no_type
                  : _no_type
                  _line_num: 39
                  _string
                    "5"
                  : _no_type
                  _line_num: 40
                  _cond
                    _line_num: 40
                    _eq
                      _line_num: 40
                      _object
                        i
                      : _no_type
                      _line_num: 40
                      _int
                        6
                      : _no_type
                    : _no_type
                    _line_num: 40
                    _string
                      "6"
                    : _no_type
                    _line_num: 41
                    _cond
                      _line_num: 41
                      _eq
                        _line_num: 41
                        _object
                          i
                        : _no_type
                        _line_num: 41
                        _int
                          7
                        : _no_type
                      : _no_type
                      _line_num: 41
                      _string
                        "7"
                      : _no_type
                      _line_num: 42
                      _cond
                        _line_num: 42
                        _eq
                          _line_num: 42
                          _object
                            i
                          : _no_type
                          _line_num: 42
                          _int
                            8
                          : _no_type
                        : _no_type
                        _line_num: 42
                        _string
                          "8"
                        : _no_type
                        _line_num: 43
                        _cond
                          _line_num: 43
                          _eq
                            _line_num: 43
                            _object
                              i
                            : _no_type
                            _line_num: 43
                            _int
                              9
                            : _no_type
                          : _no_type
                          _line_num: 43
                          _string
                            "9"
                          : _no_type
                          _line_num: 44
                          _block
                            _line_num: 44
                            _dispatch
                              _is_tail: false
                              _line_num: 44
                              _object
                                self
                              : _no_type
                              abort (
                              )
                            : _no_type
                            _line_num: 44
                            _string
                              ""
                            : _no_type
                          : _no_type
                        : _no_type
                      : _no_type
                    : _no_type
                  : _no_type
                : _no_type
              : _no_type
            : _no_type
          : _no_type
        : _no_type
      : _no_type
    _line_num: 56
    _method
      a2i (
      _line_num: 56
      _formal
        s
        : String
      )
      : Int
      _line_num: 57
      _cond
        _line_num: 57
        _eq
          _line_num: 57
          _dispatch
            _is_tail: false
            _line_num: 57
            _object
              s
            : _no_type
            length (
            )
          : _no_type
          _line_num: 57
          _int
            0
          : _no_type
        : _no_type
        _line_num: 57
        _int
          0
        : _no_type
        _line_num: 58
        _cond
          _line_num: 58
          _eq
            _line_num: 58
            _dispatch
              _is_tail: false
              _line_num: 58
              _object
                s
              : _no_type
              substr (
              _line_num: 58
              _int
                0
              : _no_type
              _line_num: 58
              _int
                1
              : _no_type
              )
            : _no_type
            _line_num: 58
            _string
              "-"
            : _no_type
          : _no_type
          _line_num: 58
          _neg
            _line_num: 58
            _dispatch
              _is_tail: false
              _line_num: 58
              _object
                self
              : _no_type
              a2i_aux (
              _line_num: 58
              _dispatch
                _is_tail: false
                _line_num: 58
                _object
                  s
                : _no_type
                substr (
                _line_num: 58
                _int
                  1
                : _no_type
                _line_num: 58
                _sub
                  _line_num: 58
                  _dispatch
                    _is_tail: false
                    _line_num: 58
                    _object
                      s
                    : _no_type
                    length (
                    )
                  : _no_type
                  _line_num: 58
                  _int
                    1
                  : _no_type
                : _no_type
                )
              : _no_type
              )
            : _no_type
          : _no_type
          _line_num: 59
          _cond
            _line_num: 59
            _eq
              _line_num: 59
              _dispatch
                _is_tail: false
                _line_num: 59
                _object
                  s
                : _no_type
                substr (
                _line_num: 59
                _int
                  0
                : _no_type
                _line_num: 59
                _int
                  1
                : _no_type
                )
              : _no_type
              _line_num: 59
              _string
                "+"
              : _no_type
            : _no_type
            _line_num: 59
            _dispatch
              _is_tail: false
              _line_num: 59
              _object
                self
              : _no_type
              a2i_aux (
              _line_num: 59
              _dispatch
                _is_tail: false
                _line_num: 59
                _object
                  s
                : _no_type
                substr (
                _line_num: 59
                _int
                  1
                : _no_type
                _line_num: 59
                _sub
                  _line_num: 59
                  _dispatch
                    _is_tail: false
                    _line_num: 59
                    _object
                      s
                    : _no_type
                    length (
                    )
                  : _no_type
                  _line_num: 59
                  _int
                    1
                  : _no_type
                : _no_type
                )
              : _no_type
              )
            : _no_type
            _line_num: 60
            _dispatch
              _is_tail: false
              _line_num: 60
              _object
                self
              : _no_type
              a2i_aux (
              _line_num: 60
              _object
                s
              : _no_type
              )
            : _no_type
          : _no_type
        : _no_type
      : _no_type
    _line_num: 68
    _method
      a2i_aux (
      _line_num: 68
      _formal
        s
        : String
      )
      : Int
      _line_num: 69
      _let
        int
        : Int
        _line_num: 69
        _int
          0
        : _no_type
        _line_num: 70
        _block
          _line_num: 71
          _let
            j
            : Int
            _line_num: 71
            _dispatch
              _is_tail: false
              _line_num: 71
              _object
                s
              : _no_type
              length (
              )
            : _no_type
            _line_num: 72
            _let
              i
              : Int
              _line_num: 72
              _int
                0
              : _no_type
              _line_num: 73
              _loop
                _line_num: 73
                _lt
                  _line_num: 73
                  _object
                    i
                  : _no_type
                  _line_num: 73
                  _object
                    j
                  : _no_type
                : _no_type
                _line_num: 74
                _block
                  _line_num: 75
                  _assign
                    int
                    _line_num: 75
                    _plus
                      _line_num: 75
                      _mul
                        _line_num: 75
                        _object
                          int
                        : _no_type
                        _line_num: 75
                        _int
                          10
                        : _no_type
                      : _no_type
                      _line_num: 75
                      _dispatch
                        _is_tail: false
                        _line_num: 75
                        _object
                          self
                        : _no_type
                        c2i (
                        _line_num: 75
                        _dispatch
                          _is_tail: false
                          _line_num: 75
                          _object
                            s
                          : _no_type
                          substr (
                          _line_num: 75
                          _object
                            i
                          : _no_type
                          _line_num: 75
                          _int
                            1
                          : _no_type
                          )
                        : _no_type
                        )
                      : _no_type
                    : _no_type
                  : _no_type
                  _line_num: 76
                  _assign
                    i
                    _line_num: 76
                    _plus
                      _line_num: 76
                      _object
                        i
                      : _no_type
                      _line_num: 76
                      _int
                        1
                      : _no_type
                    : _no_type
                  : _no_type
                : _no_type
              : _no_type
            : _no_type
          : _no_type
          _line_num: 81
          _object
            int
          : _no_type
        : _no_type
      : _no_type
    _line_num: 90
    _method
      i2a (
      _line_num: 90
      _formal
        i
        : Int
      )
      : String
      _line_num: 91
      _cond
        _line_num: 91
        _eq
          _line_num: 91
          _object
            i
          : _no_type
          _line_num: 91
          _int
            0
          : _no_type
        : _no_type
        _line_num: 91
        _string
          "0"
        : _no_type
        _line_num: 92
        _cond
          _line_num: 92
          _lt
            _line_num: 92
            _int
              0
            : _no_type
            _line_num: 92
            _object
              i
            : _no_type
          : _no_type
          _line_num: 92
          _dispatch
            _is_tail: false
            _line_num: 92
            _object
              self
            : _no_type
            i2a_aux (
            _line_num: 92
            _object
              i
            : _no_type
            )
          : _no_type
          _line_num: 93
          _dispatch
            _is_tail: false
            _line_num: 93
            _string
              "-"
            : _no_type
            concat (
            _line_num: 93
            _dispatch
              _is_tail: false
              _line_num: 93
              _object
                self
              : _no_type
              i2a_aux (
              _line_num: 93
              _mul
                _line_num: 93
                _object
                  i
                : _no_type
                _line_num: 93
                _neg
                  _line_num: 93
                  _int
                    1
                  : _no_type
                : _no_type
              : _no_type
              )
            : _no_type
            )
          : _no_type
        : _no_type
      : _no_type
    _line_num: 100
    _method
      i2a_aux (
      _line_num: 100
      _formal
        i
        : Int
      )
      : String
      _line_num: 101
      _cond
        _line_num: 101
        _eq
          _line_num: 101
          _object
            i
          : _no_type
          _line_num: 101
          _int
            0
          : _no_type
        : _no_type
        _line_num: 101
        _string
          ""
        : _no_type
        _line_num: 102
        _let
          next
          : Int
          _line_num: 102
          _divide
            _line_num: 102
            _object
              i
            : _no_type
            _line_num: 102
            _int
              10
            : _no_type
          : _no_type
          _line_num: 103
          _dispatch
            _is_tail: false
            _line_num: 103
            _dispatch
              _is_tail: false
              _line_num: 103
              _object
                self
              : _no_type
              i2a_aux (
              _line_num: 103
              _object
                next
              : _no_type
              )
            : _no_type
            concat (
            _line_num: 103
            _dispatch
              _is_tail: false
              _line_num: 103
              _object
                self
              : _no_type
              i2c (
              _line_num: 103
              _sub
                _line_num: 103
                _object
                  i
                : _no_type
                _line_num: 103
                _mul
                  _line_num: 103
                  _object
                    next
                  : _no_type
                  _line_num: 103
                  _int
                    10
                  : _no_type
                : _no_type
              : _no_type
              )
            : _no_type
            )
          : _no_type
        : _no_type
      : _no_type
    )
