_line_num: 1
_program
  _line_num: 1
  _class
    Test
    _inherits: Object
    _file_name: "casemultiplebranch.test"
    (
    _line_num: 2
    _attr
      foo
      : Test
      _line_num: 2
      _no_expr
      : _no_type
    _line_num: 3
    _method
      bar (
      )
      : Int
      _line_num: 3
      _typcase
        _line_num: 3
        _dispatch
          _is_tail: false
          _line_num: 3
          _object
            foo
          : _no_type
          bar (
          )
        : _no_type
        _line_num: 3
        _branch
          y
          : Int
          _line_num: 3
          _int
            3
          : _no_type
        _line_num: 4
        _branch
          z
          : String
          _line_num: 4
          _int
            4
          : _no_type
        _line_num: 5
        _branch
          x
          : Test
          _line_num: 5
          _int
            5
          : _no_type
      : _no_type
    )
