_line_num: 1
_program
  _line_num: 1
  _class
    Main
    _inherits: IO
    _file_name: "complex.test"
    (
    _line_num: 2
    _method
      main (
      )
      : SELF_TYPE
      _line_num: 3
      _let
        c
        Complex
        _line_num: 3
        _dispatch
          _is_tail: false
          _line_num: 3
          _new
            Complex
          : _no_type
          init (
          _line_num: 3
          _int
            1
          : _no_type
          _line_num: 3
          _int
            1
          : _no_type
          )
        : _no_type
        _line_num: 4
        _cond
          _line_num: 4
          _eq
            _line_num: 4
            _dispatch
              _is_tail: false
              _line_num: 4
              _dispatch
                _is_tail: false
                _line_num: 4
                _object
                  c
                : _no_type
                reflect_X (
                )
              : _no_type
              reflect_Y (
              )
            : _no_type
            _line_num: 4
            _dispatch
              _is_tail: false
              _line_num: 4
              _object
                c
              : _no_type
              reflect_0 (
              )
            : _no_type
          : _no_type
          _line_num: 5
          _dispatch
            _is_tail: false
            _line_num: 5
            _object
              self
            : _no_type
            out_string (
            _line_num: 5
            _string
              "=)\n"
            : _no_type
            )
          : _no_type
          _line_num: 6
          _dispatch
            _is_tail: false
            _line_num: 6
            _object
              self
            : _no_type
            out_string (
            _line_num: 6
            _string
              "=(\n"
            : _no_type
            )
          : _no_type
        : _no_type
      : _no_type
    )
  _line_num: 12
  _class
    Complex
    _inherits: IO
    _file_name: "complex.test"
    (
    _line_num: 13
    _attr
      x
      : Int
      _line_num: 13
      _no_expr
      : _no_type
    _line_num: 14
    _attr
      y
      : Int
      _line_num: 14
      _no_expr
      : _no_type
    _line_num: 16
    _method
      init (
      _line_num: 16
      _formal
        a
        Int
      _line_num: 16
      _formal
        b
        Int
      )
      : Complex
      _line_num: 17
      _block
        _line_num: 18
        _eq
          _line_num: 18
          _object
            x
          : _no_type
          _line_num: 18
          _object
            a
          : _no_type
        : _no_type
        _line_num: 19
        _eq
          _line_num: 19
          _object
            y
          : _no_type
          _line_num: 19
          _object
            b
          : _no_type
        : _no_type
        _line_num: 20
        _object
          self
        : _no_type
      : _no_type
    _line_num: 24
    _method
      print (
      )
      : Object
      _line_num: 25
      _cond
        _line_num: 25
        _eq
          _line_num: 25
          _object
            y
          : _no_type
          _line_num: 25
          _int
            0
          : _no_type
        : _no_type
        _line_num: 26
        _dispatch
          _is_tail: false
          _line_num: 26
          _object
            self
          : _no_type
          out_int (
          _line_num: 26
          _object
            x
          : _no_type
          )
        : _no_type
        _line_num: 27
        _dispatch
          _is_tail: false
          _line_num: 27
          _dispatch
            _is_tail: false
            _line_num: 27
            _dispatch
              _is_tail: false
              _line_num: 27
              _dispatch
                _is_tail: false
                _line_num: 27
                _object
                  self
                : _no_type
                out_int (
                _line_num: 27
                _object
                  x
                : _no_type
                )
              : _no_type
              out_string (
              _line_num: 27
              _string
                "+"
              : _no_type
              )
            : _no_type
            out_int (
            _line_num: 27
            _object
              y
            : _no_type
            )
          : _no_type
          out_string (
          _line_num: 27
          _string
            "I"
          : _no_type
          )
        : _no_type
      : _no_type
    _line_num: 31
    _method
      reflect_0 (
      )
      : Complex
      _line_num: 32
      _block
        _line_num: 33
        _eq
          _line_num: 33
          _object
            x
          : _no_type
          _line_num: 33
          _neg
            _line_num: 33
            _object
              x
            : _no_type
          : _no_type
        : _no_type
        _line_num: 34
        _eq
          _line_num: 34
          _object
            y
          : _no_type
          _line_num: 34
          _neg
            _line_num: 34
            _object
              y
            : _no_type
          : _no_type
        : _no_type
        _line_num: 35
        _object
          self
        : _no_type
      : _no_type
    _line_num: 39
    _method
      reflect_X (
      )
      : Complex
      _line_num: 40
      _block
        _line_num: 41
        _eq
          _line_num: 41
          _object
            y
          : _no_type
          _line_num: 41
          _neg
            _line_num: 41
            _object
              y
            : _no_type
          : _no_type
        : _no_type
        _line_num: 42
        _object
          self
        : _no_type
      : _no_type
    _line_num: 46
    _method
      reflect_Y (
      )
      : Complex
      _line_num: 47
      _block
        _line_num: 48
        _eq
          _line_num: 48
          _object
            x
          : _no_type
          _line_num: 48
          _neg
            _line_num: 48
            _object
              x
            : _no_type
          : _no_type
        : _no_type
        _line_num: 49
        _object
          self
        : _no_type
      : _no_type
    )
