_line_num: 1
_program
  _line_num: 1
  _class
    Test
    _inherits: Object
    _file_name: "dispatchonearg.test"
    (
    _line_num: 2
    _attr
      foo
      : Test
      _line_num: 2
      _no_expr
      : _no_type
    _line_num: 3
    _method
      bar (
      _line_num: 3
      _formal
        x
        : Baz
      )
      : Object
      _line_num: 3
      _dispatch
        _is_tail: false
        _line_num: 3
        _object
          foo
        : _no_type
        bar (
        _line_num: 3
        _object
          x
        : _no_type
        )
      : _no_type
    )
