_line_num: 1
_program
  _line_num: 1
  _class
    A
    _inherits: Object
    _file_name: "formallists.test"
    (
    _line_num: 2
    _method
      f (
      )
      : Int
      _line_num: 3
      _int
        5
      : _no_type
    _line_num: 5
    _method
      g (
      _line_num: 5
      _formal
        x
        : Bool
      )
      : IO
      _line_num: 6
      _object
        self
      : _no_type
    _line_num: 8
    _method
      h (
      _line_num: 8
      _formal
        y
        : SELF_TYPE
      _line_num: 8
      _formal
        z
        : Int
      )
      : SELF_TYPE
      _line_num: 9
      _object
        x
      : _no_type
    _line_num: 11
    _method
      f (
      _line_num: 11
      _formal
        a
        : Int
      _line_num: 11
      _formal
        b
        : Bool
      _line_num: 11
      _formal
        c
        : Object
      )
      : Object
      _line_num: 12
      _plus
        _line_num: 12
        _plus
          _line_num: 12
          _object
            a
          : _no_type
          _line_num: 12
          _object
            b
          : _no_type
        : _no_type
        _line_num: 12
        _object
          c
        : _no_type
      : _no_type
    )
