_line_num: 1
_program
  _line_num: 1
  _class
    Test
    _inherits: Object
    _file_name: "ifnested.test"
    (
    _line_num: 2
    _attr
      foo
      : Test
      _line_num: 2
      _no_expr
      : _no_type
    _line_num: 3
    _method
      bar (
      )
      : Int
      _line_num: 3
      _cond
        _line_num: 3
        _eq
          _line_num: 3
          _object
            x
          : _no_type
          _line_num: 3
          _int
            3
          : _no_type
        : _no_type
        _line_num: 3
        _block
          _line_num: 3
          _cond
            _line_num: 3
            _lt
              _line_num: 3
              _object
                x
              : _no_type
              _line_num: 3
              _int
                2
              : _no_type
            : _no_type
            _line_num: 3
            _new
              Foo
            : _no_type
            _line_num: 3
            _isvoid
              _line_num: 3
              _object
                baz
              : _no_type
            : _no_type
          : _no_type
        : _no_type
        _line_num: 3
        _bool
          false
        : _no_type
      : _no_type
    )
