_line_num: 1
_program
  _line_num: 1
  _class
    Goodbye
    _inherits: Object
    _file_name: "letassociativity.test"
    (
    _line_num: 3
    _method
      help (
      _line_num: 3
      _formal
        a
        : Int
      )
      : Int
      _line_num: 4
      _let
        a
        : Int
        _line_num: 4
        _no_expr
        : _no_type
        _line_num: 5
        _plus
          _line_num: 5
          _int
            6
          : _no_type
          _line_num: 5
          _int
            7
          : _no_type
        : _no_type
      : _no_type
    )
