_line_num: 1
_program
  _line_num: 1
  _class
    Test
    _inherits: Object
    _file_name: "letinit.test"
    (
    _line_num: 2
    _attr
      foo
      : Test
      _line_num: 2
      _no_expr
      : _no_type
    _line_num: 3
    _method
      baz (
      )
      : String
      _line_num: 3
      _let
        x
        Int
        _line_num: 3
        _int
          5
        : _no_type
        _line_num: 3
        _object
          x
        : _no_type
      : _no_type
    )
