_line_num: 1
_program
  _line_num: 1
  _class
    Foo
    _inherits: Object
    _file_name: "letparens.test"
    (
    _line_num: 2
    _method
      bar (
      )
      : Int
      _line_num: 2
      _block
        _line_num: 2
        _let
          a
          Int
          _line_num: 2
          _no_expr
          : _no_type
          _line_num: 2
          _plus
            _line_num: 2
            _object
              a
            : _no_type
            _line_num: 2
            _object
              b
            : _no_type
          : _no_type
        : _no_type
        _line_num: 3
        _plus
          _line_num: 3
          _let
            a
            Int
            _line_num: 3
            _no_expr
            : _no_type
            _line_num: 3
            _object
              a
            : _no_type
          : _no_type
          _line_num: 3
          _object
            b
          : _no_type
        : _no_type
        _line_num: 4
        _let
          a
          Int
          _line_num: 4
          _no_expr
          : _no_type
          _line_num: 4
          _plus
            _line_num: 4
            _object
              a
            : _no_type
            _line_num: 4
            _object
              b
            : _no_type
          : _no_type
        : _no_type
      : _no_type
    )
