_line_num: 1
_program
  _line_num: 1
  _class
    A
    _inherits: Object
    _file_name: "multipledispatches.test"
    (
    _line_num: 2
    _method
      f (
      )
      : Int
      _line_num: 2
      _block
        _line_num: 3
        _dispatch
          _is_tail: false
          _line_num: 3
          _object
            self
          : _no_type
          g (
          )
        : _no_type
        _line_num: 4
        _dispatch
          _is_tail: false
          _line_num: 4
          _object
            self
          : _no_type
          h (
          _line_num: 4
          _object
            x
          : _no_type
          )
        : _no_type
        _line_num: 5
        _dispatch
          _is_tail: false
          _line_num: 5
          _object
            self
          : _no_type
          f (
          _line_num: 5
          _int
            2
          : _no_type
          _line_num: 5
          _int
            3
          : _no_type
          )
        : _no_type
        _line_num: 6
        _dispatch
          _is_tail: false
          _line_num: 6
          _object
            self
          : _no_type
          f (
          _line_num: 6
          _int
            3
          : _no_type
          _line_num: 6
          _int
            4
          : _no_type
          _line_num: 6
          _int
            5
          : _no_type
          )
        : _no_type
        _line_num: 7
        _dispatch
          _is_tail: false
          _line_num: 7
          _object
            self
          : _no_type
          z (
          _line_num: 7
          _int
            1
          : _no_type
          _line_num: 7
          _int
            2
          : _no_type
          _line_num: 7
          _int
            3
          : _no_type
          _line_num: 7
          _int
            4
          : _no_type
          _line_num: 7
          _int
            5
          : _no_type
          )
        : _no_type
      : _no_type
    )
