_line_num: 1
_program
  _line_num: 1
  _class
    A
    _inherits: Object
    _file_name: "multipleatdispatches.test"
    (
    _line_num: 2
    _method
      f (
      )
      : Object
      _line_num: 2
      _block
        _line_num: 3
        _static_dispatch
          _is_tail: false
          _line_num: 3
          _object
            e
          : _no_type
          A
          f (
          )
        : _no_type
        _line_num: 4
        _static_dispatch
          _is_tail: false
          _line_num: 4
          _object
            e1
          : _no_type
          B
          g (
          _line_num: 4
          _int
            1
          : _no_type
          )
        : _no_type
        _line_num: 5
        _static_dispatch
          _is_tail: false
          _line_num: 5
          _object
            e2
          : _no_type
          C
          h (
          _line_num: 5
          _int
            1
          : _no_type
          _line_num: 5
          _int
            2
          : _no_type
          )
        : _no_type
        _line_num: 6
        _static_dispatch
          _is_tail: false
          _line_num: 6
          _object
            e3
          : _no_type
          D
          f (
          _line_num: 6
          _int
            1
          : _no_type
          _line_num: 6
          _int
            2
          : _no_type
          _line_num: 6
          _int
            3
          : _no_type
          )
        : _no_type
        _line_num: 7
        _dispatch
          _is_tail: false
          _line_num: 7
          _object
            x
          : _no_type
          f (
          )
        : _no_type
        _line_num: 8
        _dispatch
          _is_tail: false
          _line_num: 8
          _object
            y
          : _no_type
          g (
          _line_num: 8
          _bool
            true
          : _no_type
          _line_num: 8
          _bool
            false
          : _no_type
          )
        : _no_type
        _line_num: 9
        _dispatch
          _is_tail: false
          _line_num: 9
          _object
            z
          : _no_type
          h (
          _line_num: 9
          _int
            1
          : _no_type
          _line_num: 9
          _int
            2
          : _no_type
          _line_num: 9
          _int
            3
          : _no_type
          _line_num: 9
          _int
            4
          : _no_type
          )
        : _no_type
      : _no_type
    )
