_line_num: 1
_program
  _line_num: 1
  _class
    A
    _inherits: Object
    _file_name: "multipleattributes.test"
    (
    _line_num: 2
    _attr
      x
      : Int
      _line_num: 2
      _no_expr
      : _no_type
    _line_num: 3
    _attr
      y
      : Bool
      _line_num: 3
      _no_expr
      : _no_type
    _line_num: 4
    _attr
      z
      : Object
      _line_num: 4
      _no_expr
      : _no_type
    _line_num: 5
    _method
      f (
      )
      : Bool
      _line_num: 6
      _bool
        true
      : _no_type
    _line_num: 8
    _attr
      a
      : String
      _line_num: 8
      _no_expr
      : _no_type
    _line_num: 9
    _attr
      a
      : IO
      _line_num: 9
      _no_expr
      : _no_type
    )
