_line_num: 1
_program
  _line_num: 1
  _class
    A
    _inherits: Object
    _file_name: "nestedblocks.test"
    (
    _line_num: 3
    _method
      f (
      )
      : Int
      _line_num: 4
      _block
        _line_num: 5
        _block
          _line_num: 5
          _int
            1
          : _no_type
          _line_num: 5
          _block
            _line_num: 5
            _int
              2
            : _no_type
            _line_num: 5
            _int
              3
            : _no_type
          : _no_type
        : _no_type
        _line_num: 6
        _block
          _line_num: 6
          _block
            _line_num: 6
            _block
              _line_num: 6
              _int
                4
              : _no_type
            : _no_type
          : _no_type
        : _no_type
      : _no_type
    )
