_line_num: 1
_program
  _line_num: 1
  _class
    A
    _inherits: Object
    _file_name: "nestedlet.test"
    (
    _line_num: 2
    _method
      f (
      _line_num: 2
      _formal
        x
        Int
      )
      : Object
      _line_num: 3
      _let
        x
        Int
        _line_num: 3
        _int
          3
        : _no_type
        _line_num: 4
        _let
          y
          Bool
          _line_num: 4
          _no_expr
          : _no_type
          _line_num: 4
          _let
            z
            Object
            _line_num: 4
            _no_expr
            : _no_type
            _line_num: 5
            _let
              a
              Object
              _line_num: 5
              _no_expr
              : _no_type
              _line_num: 5
              _let
                b
                Object
                _line_num: 5
                _no_expr
                : _no_type
                _line_num: 5
                _let
                  c
                  Object
                  _line_num: 5
                  _no_expr
                  : _no_type
                  _line_num: 6
                  _let
                    d
                    Int
                    _line_num: 6
                    _int
                      6
                    : _no_type
                    _line_num: 7
                    _plus
                      _line_num: 7
                      _object
                        d
                      : _no_type
                      _line_num: 7
                      _int
                        5
                      : _no_type
                    : _no_type
                  : _no_type
                : _no_type
              : _no_type
            : _no_type
          : _no_type
        : _no_type
      : _no_type
    )
