_line_num: 1
_program
  _line_num: 1
  _class
    Test
    _inherits: Object
    _file_name: "staticdispatchnoargs.test"
    (
    _line_num: 2
    _attr
      foo
      : Int
      _line_num: 2
      _no_expr
      : _no_type
    _line_num: 3
    _method
      bar (
      )
      : Object
      _line_num: 3
      _static_dispatch
        _is_tail: false
        _line_num: 3
        _object
          self
        : _no_type
        Test
        bar (
        )
      : _no_type
    )
