_line_num: 1
_program
  _line_num: 1
  _class
    Foo
    _inherits: Object
    _file_name: "unaryassociativity.test"
    (
    _line_num: 2
    _method
      bar (
      )
      : Int
      _line_num: 2
      _block
        _line_num: 2
        _plus
          _line_num: 2
          _isvoid
            _line_num: 2
            _object
              a
            : _no_type
          : _no_type
          _line_num: 2
          _mul
            _line_num: 2
            _object
              b
            : _no_type
            _line_num: 2
            _object
              c
            : _no_type
          : _no_type
        : _no_type
        _line_num: 3
        _comp
          _line_num: 3
          _lt
            _line_num: 3
            _object
              a
            : _no_type
            _line_num: 3
            _object
              b
            : _no_type
          : _no_type
        : _no_type
        _line_num: 4
        _plus
          _line_num: 4
          _neg
            _line_num: 4
            _object
              a
            : _no_type
          : _no_type
          _line_num: 4
          _object
            b
          : _no_type
        : _no_type
      : _no_type
    )
