_line_num: 1
_program
  _line_num: 1
  _class
    Test
    _inherits: Object
    _file_name: "whileoneexpression.test"
    (
    _line_num: 2
    _attr
      foo
      : Test
      _line_num: 2
      _no_expr
      : _no_type
    _line_num: 3
    _method
      bar (
      )
      : Int
      _line_num: 3
      _loop
        _line_num: 3
        _comp
          _line_num: 3
          _bool
            false
          : _no_type
        : _no_type
        _line_num: 3
        _string
          "Ooga booga"
        : _no_type
      : _no_type
    )
